spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/joboffers
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offers:
  http:
    scheduler:
      request:
        delay: PT3H
    client:
      config:
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057

scheduling:
  enabled: true

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: jobs-offers-backend
