spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

offers:
  http:
    scheduler:
      request:
        delay: PT3H
    client:
      config:
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057

auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: jobs-offers-backend

server:
  port: 8000
